- name: Ensure andor module directory exists
  ansible.builtin.file:
    path: "{{ epics_dir }}/modules/areadetector/ADAndor"
    state: directory
    mode: '0755'

- name: Check if andor repository is already cloned
  ansible.builtin.stat:
    path: "{{ epics_dir }}/modules/areadetector/ADAndor/.git"
  register: ad_andor_repo_exists

- name: Clone andor repository {{ areadetector_iocs['ADAndor'] }}
  ansible.builtin.git:
    repo: "https://github.com/areaDetector/ADAndor"
    dest: "{{ epics_dir }}/modules/areadetector/ADAndor"
    version: "{{ areadetector_iocs['ADAndor'] }}"
  when: not ad_andor_repo_exists.stat.exists

- name: Ensure configure directory exists in andor
  ansible.builtin.file:
    path: "{{ epics_dir }}/modules/areadetector/configure"
    state: directory
    mode: '0755'

- name: Compile andor module {{ areadetector_iocs['ADAndor'] }}
  ansible.builtin.shell: |
    make
  args:
    chdir: "{{ epics_dir }}/modules/areadetector/ADAndor"

- name: Test ADAndor ioc startup
  ansible.builtin.shell: |
    timeout 30s bash -c "echo exit | iocs/andorIOC/bin/linux-x86_64/andorCCDApp"
  args:
    chdir: "{{ epics_dir }}/modules/areadetector/ADAndor"
  register: result
  failed_when: result.rc != 0