- name: Ensure devLib2 module directory exists
  ansible.builtin.file:
    path: "{{ epics_dir }}/modules/devlib2"
    state: directory
    mode: '0755'

- name: Check if devLib2 repository is already cloned
  ansible.builtin.stat:
    path: "{{ epics_dir }}/modules/devlib2/.git"
  register: devlib2_repo_exists

- name: Clone devLib2 repository {{ install_modules['devlib2'] }}
  ansible.builtin.git:
    repo: "https://github.com/epics-modules/devlib2.git"
    dest: "{{ epics_dir }}/modules/devlib2"
    version: "{{ install_modules['devlib2'] }}"
  when: not devlib2_repo_exists.stat.exists

- name: Ensure configure directory exists in devLib2
  ansible.builtin.file:
    path: "{{ epics_dir }}/modules/devlib2/configure"
    state: directory
    mode: '0755'

- name: Set EPICS_BASE in devLib2 configure/RELEASE file
  ansible.builtin.lineinfile:
    path: "{{ epics_dir }}/modules/devlib2/configure/RELEASE"
    line: "EPICS_BASE={{ epics_dir }}/base"
    create: yes

- name: Compile devLib2 module {{ install_modules['devlib2'] }}
  ansible.builtin.shell: |
    make
  args:
    chdir: "{{ epics_dir }}/modules/devlib2"
